### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by jtpio**
And drop Travis on CI.

### CODE REVIEW

**Comment by jasongrout** [comment]
Just curious: do we have a recipe for caching conda/mamba packages using the [cache action](https://github.com/actions/cache)?

**Comment by jasongrout** [comment]
> Just curious: do we have a snippet for caching conda/mamba packages using the [cache action](https://github.com/actions/cache)?

Ah, looks like the relevant info is at https://github.com/conda-incubator/setup-miniconda#caching

**Comment by bollwyvl** [comment]
Ehm... it kinda works. Conda does funky things with hardlinks, etc. that can get crazy. It's certainly been better with `actions/cache@v2`.

I did outline a slightly-over-the-top method here: https://github.com/conda-incubator/setup-miniconda/issues/155#issuecomment-805226712

**Comment by bollwyvl** [comment]
The shell thing is in the [IMPORTANT](https://github.com/conda-incubator/setup-miniconda#IMPORTANT
) note.

easiest thing on a linux-only build is a top-level:

```bash
defaults:
  run:
    shell: bash -l {0}
```

**Pull request merged**
