### PR TITLE
Add a demo workspace

### PR DESCRIPTION
**Pull request by blink1073**
Testing on https://mybinder.org/v2/gh/blink1073/jupyterlab-demo/workspace-file?urlpath=lab%2Fworkspaces%2Fdemo.

image

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I wonder if it might be better to open either (or both) of
1. The README with the Markdown renderer.
2. The FAQ widget.

**Comment by blink1073** [comment]
Thanks @ian-r-rose, updated.

**Comment by ian-r-rose** [comment]
Cool, LGTM, pending final choices on what to include in the image.

**Comment by blink1073** [comment]
Note to self: open to docs overview page instead of FAQ

**Comment by jasongrout** [comment]
One thought for the default workspace to open the docs in the right side, and the Lorenz notebook (from #60) in the left side, possibly with the lorenz.py file just below the notebook: 
screen shot 2018-02-12 at 14 09 54

**Comment by jasongrout** [comment]
Perhaps we should open the docs to the Interface section, but then it's not clear how to navigate to other sections or that the docs even do have other sections. Opening to the starting page, you can readily see the table of contents.

**Comment by jzf2101** [comment]
I think we should have the interface section and the notebook.  I worry we'll overwhelm users if we give them too much to start with.

**Comment by blink1073** [comment]
We can't link to a specific page in the documentation without a change to jlab itself

**Comment by jasongrout** [comment]
> We can't link to a specific page in the documentation without a change to jlab itself

Good point.

**Comment by jzf2101** [comment]
Maybe we need to add a link in the readme instead?

**Comment by jasongrout** [comment]
@blink1073 - I pushed the workspace update to your branch to open the Lorenz file and the docs, like in the above screenshot. Thoughts? Do you think we should open the readme or some other file instead?

**Comment by blink1073** [comment]
I think Lorenz and the docs are a good combo

**Comment by jasongrout** [comment]
Something isn't quite working right with the widgets - they only show up on the second time or so of executing the appropriate cell. I'm investigating...

**Pull request merged**
