### PR TITLE
Lightning in Japan

### LINKED ISSUE #30: Geojson of lightning strikes
We could include a geojson file of lightning strikes, and maybe a large csv of them, you know, for lightning talks :). It'd be fun to give a talk where the data was all puns on lightning talks.

### PR DESCRIPTION
**Pull request by jzf2101**
Closes #30 @jasongrout  ⚡️ 🇯🇵 

See [copyright info](http://www.jma.go.jp/jma/en/copyright.html)

> The Terms of Use are compatible with the Creative Commons Attribution License 4.0 (hereinafter referred to as the CC License). This means that Content based on the Terms of Use may be used under the CC License in lieu of the Terms of Use.

### CODE REVIEW

**Comment by jasongrout** [comment]
Since this would be distributed with this repo, we should follow the CC rules and give appropriate attribution in our LICENSE file.

**Comment by jasongrout** [comment]
OR we could have our script get this file, without actually distributing it with our repo.

**Comment by jzf2101** [comment]
See #14 @jasongrout

**Comment by jzf2101** [comment]
Also closes #7

**Pull request merged**
