### PR TITLE
Upgrade to jupyterlab 0.30.0

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by gnestor** [comment]
The binder build is failing with:

```
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - r-ggplot2
Use "conda info <package>" to see the dependencies for each package.


Removing intermediate container 8a9c4df74935
The command '/bin/sh -c ./postBuild' returned a non-zero code: 1
```

https://mybinder.org/v2/gh/gnestor/jupyterlab-demo/0.30.0?urlpath=lab

**Comment by blink1073** [comment]
The only difference I can spot from the `.travis.yml` file is `conda update -q conda`.

**Comment by blink1073** [comment]
@ian-r-rose, I had to remove the google drive extension.  :(

```
Not a valid origin for the client: https://hub.mybinder.org has not been whitelisted for client ID 625147942732-t30t8vnn43fl5mvg1qde5pl84603dr6s.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID.
```

**Comment by blink1073** [comment]
One more change coming...

**Comment by blink1073** [comment]
Note that we'll be able to point the url to `/lab/tree/demo` and open with the demo files ready to roll pending https://github.com/jupyterlab/jupyterlab/pull/3396.

**Comment by blink1073** [comment]
This is gtg, and gorgeous:

image

**Comment by blink1073** [comment]
Actually, there's a couple of files missing that I'd like to add.

**Comment by blink1073** [comment]
Will have to wait until after the gym 🏋️ .

**Comment by ian-r-rose** [comment]
Ah, I can whitelist `hub.mybinder.org` for the default client ID in the `google-drive` extension. I also expect that anything we point people to on mybinder that uses the `github` extension will be rate-limited *very* soon (until I can turn it into a full-fledget OAuth app).

**Comment by ian-r-rose** [comment]
I have verified that the google-drive extension now works with this branch on mybinder.

**Comment by blink1073** [comment]
Great!  I'll verify on the next build.

**Comment by blink1073** [comment]
Do you recommend not using the `github` extension here then?

**Comment by ian-r-rose** [comment]
I expect that this is not a good use case, so I'd recommend removing it. Unauthenticated requests are limited to 60/hr for a given IP address (which is essentially zero -- a single person can hit this within a few minutes, let alone everyone who is using mybinder).

I have set it up so that you can add credentials in a notebook serverextension, but since mybinder is based off of public repos, one would need to keep private credentials in an public place.

**Comment by jasongrout** [comment]
Looks like we need to also tell people we need to install pyyaml in the readme.

**Comment by blink1073** [comment]
Let's merge and iterate on this.

**Pull request merged**
