### PR TITLE
Drop QuantStack channel and only use conda-forge

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Now possible since the rebuild.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks for the simplification @SylvainCorlay. This looks good, except that the appveyor failure looks legitimate (it couldn't find `xeus-cling`). Is it possible that it hadn't made its way through the feedstock yet, or is something wrong with the windows build?

I've kicked the CI in case it's the former.

**Comment by SylvainCorlay** [comment]
@ian-r-rose cling and xeus-cling are not yet packaged for windows on conda-forge. It is probably not going to be in the very near future. The QuantStack channel builds exist but they are in fact not fully functional because cling 0.5 does not support windows.

**Comment by SylvainCorlay** [comment]
I am currious why we check the environment with appveyor since binder is linux only?

**Comment by vidartf** [comment]
It would be nice if the demo continues to work on Windows! I have a small demo I want to do this week, and I cannot rely on internet being present at the site.

**Comment by SylvainCorlay** [comment]
The thing is that the cling interpreter is not really supported on windows, so whatever build was there is not really functional.

I would be nice to be able to specify that a requirement is only required on a certain platform...

**Comment by SylvainCorlay** [comment]
Yeah! Thanks @ian-r-rose for pushing this forward.

**Comment by ian-r-rose** [comment]
Sorry for the extremely slow merge on this @SylvainCorlay, and thanks for the updates! In the interests of getting the binder back up-and-running, we'll just move forwards here without Windows builds, and figure that out later.

**Comment by ian-r-rose** [comment]
@SylvainCorlay I am currently seeing something broken with the xleaflet map in the C++ notebook -- does anything strike you as wrong with the current versions?

**Comment by SylvainCorlay** [comment]
I am afk (replying from my phone). You may need to update ipyleaflet as well.

**Comment by SylvainCorlay** [comment]
(Fornthe semver range check to pass, if this is the issue that you are seeing in the js console)

**Comment by ian-r-rose** [comment]
Ah, yep, I see the semver error in the console, good call.

**Pull request merged**
