### PR TITLE
Improve xeus notebook

### PR DESCRIPTION
**Pull request by SylvainCorlay**
URL for built binder:

https://mybinder.org/v2/gh/SylvainCorlay/jupyterlab-demo/improve-xeus-notebook?urlpath=lab/

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ok, all is working!

**Comment by ian-r-rose** [comment]
Hi @SylvainCorlay, sorry, let this go long enough that there is a merge conflict. Can you rebase?

**Comment by SylvainCorlay** [comment]
Pinning R is becoming necessary as the conda-forge build for 3.5 misses the png support.

**Comment by SylvainCorlay** [comment]
@ian-r-rose this is ready to go.

The red cross on appveyor is due to the pinning of r-base to a build that does not exist on windows.

**Comment by SylvainCorlay** [comment]
@ian-r-rose 
Merge!

**Comment by blink1073** [comment]
Nice!

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab/commit/72a0823dd0dd0a2bdde7cc85a709cc3b3e90ff07

**Comment by ian-r-rose** [comment]
Thanks @SylvainCorlay!

**Pull request merged**
