### PR TITLE
Jupyterlab 1.0

### PR DESCRIPTION
**Pull request by ian-r-rose**
Updates to JupyterLab 1.0.

Also uses the workspaces CLI to open up the Lorenz notebook and the JupyterLab documentation side-by-side upon launching binder.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!  Not sure what the CI fail is; I'll review in the morning

**Comment by jasongrout** [comment]
I updated widgets as well here.

**Comment by jasongrout** [comment]
Recent xeus-cling is not available on windows, apparently, so any windows CI will fail.

**Comment by choldgraf** [comment]
Just another note here - please tell the Binder team when you merge this, we are likely going to need to ban the jupyterlab repository until the build finishes otherwise it'll flood Binder w/ builds

**Comment by jasongrout** [comment]
Appveyor says:

```
Solving environment: ...working... failed
ResolvePackageNotFound: 
  - xeus-cling=0.6
Could not find conda environment: jupyterlab-demo

```
but it is right here: https://anaconda.org/conda-forge/xeus-cling/files

Travis seems to find it. Any reason why appveyor isn't finding it?

**Comment by ian-r-rose** [comment]
@jasongrout It's unavailable on Windows, as far as I know. So the Appveyor failure is, unfortunately, expected.

See some further discussion here: https://github.com/jupyterlab/jupyterlab-demo/pull/81

**Comment by jasongrout** [comment]
Thanks. I was confusing running repo2docker on windows (which should work) vs just building the env on windows.

**Comment by ian-r-rose** [comment]
So...perhaps it's close-to-ban-time @choldgraf?

**Comment by jasongrout** [comment]
Here's the binder for the most recent commit: [Binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/c6ff54a8ca1b5d4d42aa1d03d18e32cbefc5df1e)

**Comment by choldgraf** [comment]
@jasongrout is the plan to link to the branch instead of master? If so that would make binder issues much more manageable

**Comment by jasongrout** [comment]
We were going to merge and link to the merge commit

**Comment by jasongrout** [comment]
Though we could just link to this commit right here that is already built, since it should basically be a fast-forward merge

**Comment by choldgraf** [comment]
perfect, that works great - anything other than master :-)

**Comment by jasongrout** [comment]
Okay, everything works great from my testing of the binder. Merging!

**Comment by jasongrout** [comment]
I'm building the binder for the merge commit right now.

**Comment by jasongrout** [comment]
Okay, we can link directly to:

```
https://gke.mybinder.org/v2/gh/ian-r-rose/jupyterlab-demo/c6ff54a8ca1b5d4d42aa1d03d18e32cbefc5df1e?urlpath=lab/tree/demo/Lorenz.ipynb
```
for now, while master is still building

**Comment by choldgraf** [comment]
@jasongrout just a note that you in general shouldn't like to `gke.mybinder.org`, just link to `mybinder.org`

**Comment by jasongrout** [comment]
Thanks. I realized that before we put the actual link up :).

Things are live now on try.jupyter.org, pointing to a new stable tag in the demo repo.

**Comment by jasongrout** [comment]
We haven't published a blog post, but we did just announce at scipy. I'm curious how popular the jlab binders are over the next week or so.

**Comment by ian-r-rose** [comment]
Thanks for finishing this off @jasongrout!

**Pull request merged**
