### PR TITLE
Switch to JupyterLab 4

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes https://github.com/jupyterlab/jupyterlab-demo/issues/49

https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/lab-4.0?urlpath=lab

@krassowski I was looking at modernizing this package by merging the opened PRs.

I will left aside the upgrade to 4 to be the focus of this branch. Let me know if I can help.

:warning: this removes the R kernel.

### CODE REVIEW

**Comment by krassowski** [comment]
Giving up on xeus stack:

```
Could not solve for environment specs
The following packages are incompatible
├─ xeus-cling 0.15.1**  is installable and it requires
│  └─ cppzmq >=4.9.0,<4.10.0a0 , which can be installed;
└─ xleaflet   is uninstallable because there are no viable options
   ├─ xleaflet [0.10.0|0.5.0|...|0.9.0] would require
   │  └─ xeus [>=0.17.0,<0.18.0a0 |>=0.18.1,<0.19.0a0 |>=0.19.1,<0.20.0a0 |>=0.20.0,<0.21.0a0 |>=0.21.1,<0.22.0a0 ], which requires
   │     └─ cppzmq >=4.3.0,<4.4.0a0 , which conflicts with any installable versions previously reported;
   ├─ xleaflet 0.11.0 would require
   │  └─ xeus >=0.23.3,<0.24.0a0  but there are no viable options
   │     ├─ xeus [0.17.0|0.18.1|...|0.23.5], which cannot be installed (as previously explained);
   │     ├─ xeus [0.23.10|0.23.12|...|0.24.1] would require
   │     │  └─ cppzmq >=4.6.0,<4.7.0a0 , which conflicts with any installable versions previously reported;
   │     └─ xeus [0.23.5|0.23.6] would require
   │        └─ cppzmq >=4.4.1,<4.5.0a0 , which conflicts with any installable versions previously reported;
   ├─ xleaflet 0.11.1 would require
   │  └─ xeus >=0.23.14,<0.24.0a0 , which cannot be installed (as previously explained);
   ├─ xleaflet [0.11.1|0.11.2] would require
   │  └─ xeus >=0.24.1,<0.25.0a0  but there are no viable options
```

etc.

**Comment by andrii-i** [comment]
"Interactive Widgets" section of [demo/notebooks/Cpp.ipynb](https://github.com/jupyterlab/jupyterlab-demo/blob/master/notebooks/Cpp.ipynb)  relies on xeus stack so we might want to temporary remove that part of the demo notebook. Everything else works great, thank you for working on this @krassowski.

**Comment by andrii-i** [comment]
Binder is not caching the image (probably due to limited capacity) and has to build it every time with ~75% failure rate for me. Is it the same on your end?

**Comment by manics** [comment]
I wouldn't rely on binder at the moment, as we're still having problems due to a reduction in capacity and some configuration issues with the other hosts. If it mostly works with mybinder, or at least with repo2docker, that's probably good enough.

**Comment by fcollonval** [comment]
> * the workspace restoration does not work (it did not work prior to this PR either)

I fix this on master and rebase to fix it here too.

**Comment by andrii-i** [comment]
@fcollonval, @krassowski thank you for working on this

**Pull request merged**
