### PR TITLE
Add the Lorenz differential equation notebooks we use in screenshots.

### PR DESCRIPTION
**Pull request by jasongrout**
This is a simplified notebook from the poster-child example for the notebook, the ipywidgets Lorenz demonstration. I simplified it slightly to make it easy to take a screenshot containing both the equations and the interact.

CC @ellisonbg

### CODE REVIEW

**Comment by jzf2101** [comment]
@jasongrout don't we need `lorenz.py`?

**Comment by jasongrout** [comment]
Yes, it's here.

**Comment by jasongrout** [comment]
https://github.com/jasongrout/jupyterlab-demo/blob/2827cb897abbd812d51799811208b724a84fbc27/notebooks/lorenz.py

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
