### PR TITLE
Update to JupyterLab 2.0

### PR DESCRIPTION
**Pull request by jtpio**
Fixes https://github.com/jupyterlab/jupyterlab/issues/8208

Update to JupyterLab 2.0 and bump a few other widget dependencies.

To test this PR on Binder:

[Binder](https://mybinder.org/v2/gh/jtpio/jupyterlab-demo/jlab-2?urlpath=%2Flab)

### CODE REVIEW

**Comment by blink1073** [comment]
Do you mind trying to upgrade [miniconda](https://github.com/jupyterlab/jupyterlab-demo/blob/71b616307dcb9cba18262d8e5fa46ad828ca51e4/appveyor.yml#L7) to python 3.7 to fix the appveyor issue?

**Comment by jtpio** [comment]
Done, let's see how it goes.

**Comment by jtpio** [comment]
Now the error seems to be caused by `xeus-cling` that can't be installed on Windows.

It looks like this has already been discussed in https://github.com/jupyterlab/jupyterlab-demo/pull/81

**Comment by blink1073** [comment]
I'd say let's drop appveyor.yml, there's no urgent need for the demo to be built on Windows.

**Comment by jtpio** [comment]
That sounds reasonable. For reference this was also the case when updating to JupyterLab 1.0: https://github.com/jupyterlab/jupyterlab-demo/pull/91

I'll remove appveyor and trigger another Binder build.

**Comment by blink1073** [comment]
Appveyor failure is expected until we merge this.  The Travis failure seemed like a connectivity issue, kicked it.

**Comment by blink1073** [comment]
Thanks @jtpio!

**Comment by saulshanabrook** [comment]
@jtpio i think the error is because the version of `jupyterlab_server` is too old in binder. It needs to be at least 1.1.0: https://github.com/jupyterlab/jupyterlab/pull/8127 and it's 1.0.6.

I am not sure why it's pulling in an old version.

**Comment by jtpio** [comment]
This should fix it: https://github.com/conda-forge/jupyterlab-feedstock/pull/213

**Comment by jtpio** [comment]
To add more context, the issue mentioned here is this one: https://github.com/jupyterlab/jupyterlab/issues/8231

**Pull request merged**
