### PR TITLE
Move binder-data to their own folder to clean up the root.

### PR DESCRIPTION
**Pull request by ian-r-rose**
I think this is a little cleaner.

### CODE REVIEW

**Comment by blink1073** [comment]
Let's also bump the jlab version here, I'll let you know when the Linux packages are ready.

**Comment by blink1073** [comment]
The use of `environment.yml` file needs updating [here](https://github.com/jupyterlab/jupyterlab-demo/blob/master/tasks.py#L39), and we should also move the workspace file.

**Comment by ian-r-rose** [comment]
As long as we are not using it at the moment, maybe we should remove the workspace file?

**Comment by blink1073** [comment]
Yeah, and remove the line in `postBuild`

**Comment by blink1073** [comment]
I think the lorenz files need to stay in place, but update `talks.yml` to rename them appropriately.

**Comment by ian-r-rose** [comment]
Okay, looks like we are in business

**Comment by jasongrout** [comment]
This works well for me. Thanks!

**Comment by jasongrout** [comment]
Since we use this repo for more than just binder, I think I'd prefer the directory be `environment` or something, but it doesn't matter a huge amount to me either.

**Comment by ian-r-rose** [comment]
It has to be named binder for `mybinder.org` to pick it up.

**Comment by jasongrout** [comment]
ah, thanks.

**Pull request merged**
